version: '3'
services:
  backup-manager:
    image: mmmaxwwwell/backup-manager
    container_name: backup-manager
    restart: always
    volumes:
      - ./appdata/backup-manager/local_backup:/home/node/app/local_backup
      - ./appdata/backup-manager/storage:/home/node/app/storage
      - ./appdata/space-engineers/config:/home/node/app/backup_source
    env_file:
      - ./settings/backup-manager.env
  se-server:
    image: mmmaxwwwell/space-engineers-dedicated-docker-linux:wine6
    container_name: space-engineers-dedicated-docker-linux
    restart: always
    volumes:
      - ./appdata/space-engineers/config/World:/appdata/space-engineers/World
      - ./appdata/space-engineers/config/Plugins:/appdata/space-engineers/Plugins
      - ./appdata/space-engineers/config/SpaceEngineers-Dedicated.cfg:/appdata/space-engineers/SpaceEngineersDedicated/SpaceEngineers-Dedicated.cfg
      - ./appdata/space-engineers/bins/SpaceEngineersDedicated:/appdata/space-engineers/SpaceEngineersDedicated
      - ./appdata/space-engineers/bins/steamcmd:/home/wine/.steam
    ports:
     - "27016:27016/udp"
